animal = " CHanchito feliz gordote "
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.rstrip())
print(animal.lstrip())
print(animal.find(" "))
print(animal.replace("CH", "j"))
print("C" in animal)
print("C" not in animal)
